name: smarthome-ci

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v5

    - name: Setup .NET 10
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '10.0.x'

    - name: Restore Dependencies
      working-directory: ./application
      run: dotnet restore

    - name: Build
      working-directory: ./application
      run: dotnet build --no-restore --configuration Release

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v5
      with:
        name: build-output
        path: application/

  test:
    name: Run Tests
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v5

    - name: Setup .NET 10
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '10.0.x'
    
    - name: Download Build Artifacts
      uses: actions/download-artifact@v5
      with:
        name: build-output
        path: application/

    - name: Restore Dependencies
      working-directory: ./application
      run: dotnet restore

    - name: Run Tests
      working-directory: ./application
      run: dotnet test tests/SmartHome.Tests.csproj --no-restore --configuration Release
